### ISSUE TITLE
Question on video sequence. 

### ISSUE THREAD

**Issue by tyiannak** [theopsall/video_annotator#4]
How are the videos prompt to the user? It seems that a random  video is shown every time without keeping a list of the already annotated videos? If this is the case, wouldn't it be better to randomly select only from the non-annotated videos?

**Comment by theopsall** [comment]
@tyiannak, yes you are right, the video random selection comes from the non-already annotated list. The function that does this did not update the log again. It seems to works now.

**Comment by tyiannak** [comment]
works just fine now thanx!
